[package]
name = "referral-module"
version = "0.1.0"
edition = "2021"
authors = [
    "Vlad Nedelcu <vlad.nedelcu@stakegold.com>",
    "Alex Jilavu <alex.jilavu@stakegold.com>"
]

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.38.0"