// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           15
// Async Callback (empty):               1
// Total number of exported functions:  17

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    tests
    (
        addPaymentToken
        removePaymentToken
        registerReferralTag
        claimReferralFees
        updateTier
        addTierDetails
        removeTierDetails
        setReferralFeePercentage
        removeReferralTag
        getCollectedFeeAmount
        getUserTag
        getReferralFeePercentage
        getTierDetails
        getTagAccumulatedVolume
        getWrappedToken
    )
}

elrond_wasm_node::wasm_empty_callback! {}
